all:
  vars:
    control_plane_endpoint: 192.168.3.100
    load_balancer_ip_pool:
      - 192.168.0.240/28
    ntp_server: "ntp.ubuntu.com"
    # Used for tailscale k8s node
    tailscale_auth_key: "tskey-auth-..."
    # Used for tailscale-operator
    tailscale_client_id: "xxxxx"
    tailscale_client_secret: "tskey-client-..."
    # TODO:
    registries_config_yaml: |
      mirrors:
        "*":
        docker.io:
          endpoint:
            - "https://registry-1.docker.io"
metal:
  children:
    masters:
      hosts:
        daten-jumper-0:
          ansible_host: 192.168.0.98
          mac: "f4:4d:30:8e:85:19"
          disk: sda
          network_interface: eno1
