all:
  vars:
    control_plane_endpoint: 192.168.0.100
    load_balancer_ip_pool:
      - 192.168.0.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.0.201, mac: '94:c6:91:39:d5:df', disk: sda, network_interface: enp1s0f0}
        metal1: {ansible_host: 192.168.0.202, mac: '10:e7:c6:c4:68:e0', disk: sda, network_interface: eno1}
        metal2: {ansible_host: 192.168.0.203, mac: 'f4:4d:30:8e:85:19', disk: sda, network_interface: eno1}
