elementweb:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: "homelab-tunnel.amorim.pro"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    hosts:
      - host: &frontend_host chat.amorim.pro
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: element-tls-certificate
        hosts:
          - *frontend_host
  config:
    default:
      base_url: https://matrix.amorim.pro
      server_name: amorim.pro

dendrite:
  dendrite_config:
    global:
      server_name: matrix.amorim.pro
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hostName: matrix.amorim.pro
    tls:
      - hosts:
          - matrix.amorim.pro
        secretName: matrix-tls-certificate
  postgresql:
    enabled: true
